"""G1 and G1b: run-time route-local gates on the action a route actually executes.

Protocol section 8.  These are RUN-TIME gates, deliberately distinct from the
BUILD-TIME packet checks S1-S6 / L1-L3 in `packet_schema.py`, which test the
sealed packet before it is sealed.  Section 4.1 keeps the two families as
separate identifiers on purpose; the resemblance of some logic is not a reason to
let one stand as evidence for the other, and nothing here imports that module.

G1 and G1b are also kept as separate identifiers even though they share
primitives, because they establish different propositions:

    G1   the constructed group is a group of the right size, with conjugacy
         classes partitioning that order.
    G1b  the ACTION is an effective, free, correctly de-duplicated action of that
         group on S^3.

A malformed pair representation that silently yields an orbifold, or that
double-counts the deck group through the central kernel, PASSES G1 and FAILS
G1b.  That asymmetry is the whole reason G1b exists, and it is mutation 3 below.

SHARING.  Section 2 permits the routes to share raw action pairs, coordinate
conventions and generic linear-algebra utilities.  This module is outside that
literal list, so per the standing test in `SHARING_BOUNDARY.md` it is DECLARED
here: it carries no characters, invariant dimensions, multiplicities, projectors,
reduced operators, symmetry-adapted bases, spectral fixtures or expected answers.
It computes properties of the ACTION only, never of the spectrum.  Each route
calls it on the action IT executes; the gate never certifies one route's action
on behalf of the other.

EXPECTED-ORDER RULE (section 8, G1b evidence-strength note).  The declared order
from Packet I may NOT be used as an expected-order fixture by either primary
route.  `effective_order` is DERIVED by closure here.  Comparison against a
declared order is offered separately as `metadata_consistency`, is labelled as
such, and is never part of the derivation.
"""

import numpy as np

__all__ = [
    "left_matrix", "right_matrix", "isometry_matrix",
    "close_action", "element_order", "acts_freely",
    "G1_group_construction", "G1b_effective_action",
]

TOL = 1e-9


# --- primitives: the action as 4x4 rotations ---------------------------------

def left_matrix(u):
    """L(u) with L(u) b = u * b, for unit quaternions as (w, x, y, z)."""
    w, x, y, z = u
    return np.array([
        [w, -x, -y, -z],
        [x,  w, -z,  y],
        [y,  z,  w, -x],
        [z, -y,  x,  w],
    ])


def right_matrix(v):
    """R(v) with R(v) a = a * v."""
    w, x, y, z = v
    return np.array([
        [w, -x, -y, -z],
        [x,  w,  z, -y],
        [y, -z,  w,  x],
        [z,  y, -x,  w],
    ])


def isometry_matrix(pair):
    """The 4x4 rotation of x -> u x v.

    This is the canonicalization surface section 8 requires: L(-u) R(-v) equals
    L(u) R(v) identically, so [u, v] and [-u, -v] produce the SAME matrix and
    cannot inflate the apparent order.  Canonicalizing here, on the generated
    group, is what makes the central identification automatic rather than a
    special case applied to the input generators.
    """
    u, v = pair
    return left_matrix(np.asarray(u, dtype=float)) @ right_matrix(np.asarray(v, dtype=float))


def close_action(pairs, cap=2000, tol=TOL):
    """Close the action generated by `pairs`, as 4x4 rotations.

    Returns the list of distinct rotation matrices.  Closure runs on the
    matrices, so the two-to-one central identification is absorbed by
    construction: adding [-u, -v] alongside [u, v] cannot change the result.
    """
    gens = [isometry_matrix(p) for p in pairs]
    ident = np.eye(4)
    elems = [ident]

    def known(M):
        return any(np.abs(M - E).max() < tol for E in elems)

    frontier = [ident]
    while frontier:
        nxt = []
        for A in frontier:
            for G in gens:
                B = A @ G
                if not known(B):
                    elems.append(B)
                    nxt.append(B)
                    if len(elems) > cap:
                        raise ValueError("closure exceeded cap")
        frontier = nxt
    return elems


def element_order(M, cap=2000, tol=TOL):
    """Smallest k >= 1 with M^k = I."""
    P = M.copy()
    for k in range(1, cap + 1):
        if np.abs(P - np.eye(4)).max() < tol:
            return k
        P = P @ M
    raise ValueError("element order exceeded cap")


def acts_freely(M, tol=1e-7):
    """True if the rotation has NO fixed point on S^3.

    Section 8 requires this VERIFIED rather than inferred from the declared
    parameters: a fixed point exists exactly when the 4x4 rotation has an
    eigenvalue +1.  Checking the spectrum tests the matrix actually executed,
    which is the object a malformed pair representation corrupts.
    """
    ev = np.linalg.eigvals(M)
    return not np.any(np.abs(ev - 1.0) < tol)


def _conjugacy_classes(elems, tol=TOL):
    """Partition the group into conjugacy classes."""
    n = len(elems)
    unassigned = set(range(n))
    classes = []
    while unassigned:
        i = min(unassigned)
        A = elems[i]
        cls = set()
        for g in elems:
            C = g @ A @ g.T          # g is orthogonal, so g^-1 = g^T
            for j in list(unassigned):
                if np.abs(C - elems[j]).max() < tol:
                    cls.add(j)
                    break
        classes.append(sorted(cls))
        unassigned -= cls
    return classes


# --- G1 ----------------------------------------------------------------------

def G1_group_construction(pairs, expected_order=None):
    """G1: closed, of the derived order, with conjugacy classes partitioning it.

    `expected_order` is OPTIONAL and, when supplied, is reported as a labelled
    metadata-consistency comparison.  It is never used to derive the order.
    """
    elems = close_action(pairs)
    order = len(elems)

    closed = True
    for A in elems[: min(order, 40)]:
        for B in elems[: min(order, 40)]:
            if not any(np.abs(A @ B - E).max() < TOL for E in elems):
                closed = False
                break
        if not closed:
            break

    classes = _conjugacy_classes(elems)
    partitions = sum(len(c) for c in classes) == order and \
        len({i for c in classes for i in c}) == order

    result = {
        "gate": "G1",
        "derived_order": order,
        "closed_under_multiplication": closed,
        "conjugacy_classes": len(classes),
        "classes_partition_order": partitions,
        "pass": bool(closed and partitions),
    }
    if expected_order is not None:
        result["metadata_consistency"] = {
            "declared_order": expected_order,
            "agrees": order == expected_order,
            "note": "labelled comparison; the order above is derived by closure",
        }
    return result


# --- G1b ---------------------------------------------------------------------

def G1b_effective_action(pairs, expected_order=None, expected_census=None):
    """G1b: effective, freely acting, correctly de-duplicated action.

    Checks, each independently falsifiable:
      1. effective order derived by closing the 4x4 rotations;
      2. central identification absorbed: adding [-u, -v] for every generator
         leaves the closure order unchanged;
      3. every NONIDENTITY element acts freely, verified as absence of an
         eigenvalue +1;
      4. element-order census.
    """
    elems = close_action(pairs)
    order = len(elems)

    negated = list(pairs) + [((-np.asarray(u, dtype=float)).tolist(),
                              (-np.asarray(v, dtype=float)).tolist())
                             for (u, v) in pairs]
    order_with_negatives = len(close_action(negated))
    central_absorbed = (order_with_negatives == order)

    ident = np.eye(4)
    nonidentity = [M for M in elems if np.abs(M - ident).max() >= TOL]
    fixed_point_elements = [i for i, M in enumerate(nonidentity) if not acts_freely(M)]
    free = not fixed_point_elements

    census = {}
    for M in elems:
        k = element_order(M)
        census[k] = census.get(k, 0) + 1

    result = {
        "gate": "G1b",
        "effective_order": order,
        "order_with_central_negatives_added": order_with_negatives,
        "central_identification_absorbed": central_absorbed,
        "acts_freely": free,
        "elements_with_fixed_points": len(fixed_point_elements),
        "element_order_census": dict(sorted(census.items())),
        "pass": bool(central_absorbed and free),
    }
    if expected_order is not None:
        result["metadata_consistency"] = {
            "declared_order": expected_order,
            "agrees": order == expected_order,
            "note": "labelled comparison; effective_order above is derived by "
                    "closing the raw action pairs, never taken from the declaration",
        }
    if expected_census is not None:
        agrees = {int(k): v for k, v in census.items()} == \
                 {int(k): v for k, v in expected_census.items()}
        result["census_matches_frozen"] = agrees
        result["pass"] = bool(result["pass"] and agrees)
    return result


# --- binding the certified group to whatever consumes it ---------------------

def effective_group_digest(elems, places=10):
    """A canonical digest of an effective group, as a set of 4x4 rotations.

    Exists so a consumer that AVERAGES over the group can prove it averaged over
    the very group G1b certified, rather than over a separately-closed one that
    happens to have the same order.  Two closures agreeing on order is weak;
    agreeing on this digest is element-identity.

    Canonicalization: entries rounded to `places` decimals, `-0.0` normalized to
    `0.0`, rows flattened, matrices sorted lexicographically, then SHA-256 over a
    separator-free ASCII rendering.  Order-independent by construction, since a
    group is a set and closure order is an implementation detail.
    """
    import hashlib

    def norm(M):
        return tuple(round(float(x), places) + 0.0 for x in np.asarray(M).ravel())

    rows = sorted(norm(M) for M in elems)
    payload = ";".join(",".join(f"{x:.{places}f}" for x in r) for r in rows)
    return hashlib.sha256(payload.encode("ascii")).hexdigest()


def certified_effective_group(pairs):
    """Run G1b and return (verdict, effective elements, digest).

    The single call a producer should use: it cannot average over a group that
    G1b has not passed, because the elements and the digest come back from the
    same closure the gate inspected.
    """
    elems = close_action(pairs)
    verdict = G1b_effective_action(pairs)
    return verdict, elems, effective_group_digest(elems)
