"""Items 0 and 1: group from generators, derived subgroup, <3 3; 3 -3|6 0>, Hom dimensions."""
import json

import numpy as np
import sympy as sp

import lib
import sectors

C = lib.Checker("item01")
res = {}

# ---- 0(a)
n1 = lib.qnorm2(lib.Q1)
n2 = lib.qnorm2(lib.Q2)
print("|q1|^2 =", n1, " |q2|^2 =", n2)
C.check("|q1|^2 == 1 exactly", lambda z: z == lib.Q5(1), n1, n1 + lib.Q5(0, 1), "add sqrt5")
C.check("|q2|^2 == 1 exactly", lambda z: z == lib.Q5(1), n2, n2 * lib.Q5(2), "double it")
G = lib.group()
order = len(G)
print("order of Gamma:", order)
Gs = set(G)
closed = all(lib.qmul(a, b) in Gs for a in G for b in G)
C.check("Gamma closed under multiplication", lambda z: z, closed,
        all(lib.qmul(a, b) in (Gs - {G[5]}) for a in G for b in G), "remove one element")
comms = {lib.qmul(lib.qmul(a, b), lib.qmul(lib.qconj(a), lib.qconj(b))) for a in G for b in G}
Dg = lib.closure(list(comms))
print("derived subgroup order:", len(Dg), " number of distinct commutators:", len(comms))
perfect = (len(Dg) == order)
C.check("derived subgroup order == |Gamma|", lambda z: z[0] == z[1], (len(Dg), order),
        (len(lib.closure([lib.Q1])), order), "use subgroup generated by q1 only")
# element orders and class structure (derived, for the record)
def elt_order(q):
    p, k = q, 1
    while p != lib.QID:
        p, k = lib.qmul(p, q), k + 1
    return k
ords = {}
for q in G:
    o = elt_order(q)
    ords[o] = ords.get(o, 0) + 1
classes = lib.conj_classes(G)
print("element orders histogram:", dict(sorted(ords.items())))
print("class sizes:", [len(c) for c in classes], " traces 2w:",
      [str(sp.nsimplify((2 * c[0][0]).sym())) for c in classes])
res["item0"] = {"norm_q1_sq": str(n1), "norm_q2_sq": str(n2), "order": order,
                "derived_subgroup_order": len(Dg), "perfect": perfect,
                "order_q1": elt_order(lib.Q1), "order_q2": elt_order(lib.Q2),
                "element_order_hist": ords, "class_sizes": [len(c) for c in classes]}

# ---- 0(b)
v = lib.cg(3, 3, 3, -3, 6, 0)
vl = lib.cg_lowering_table(3, 3, 6)[(3, -3, 0)]
print("<3 3; 3 -3|6 0> =", v, "=", sp.N(v, 20), " lowering construction:", vl)
C.check("Racah and lowering agree on <3 3;3 -3|6 0>", lambda z: sp.simplify(z[0] - z[1]) == 0,
        (v, vl), (v, -vl), "flip sign of lowering value")
res["item0"]["cg_33_3m3_60"] = str(v)
res["item0"]["cg_33_3m3_60_float"] = float(v)

# ---- 1: exact characters and Hom dimensions
P, info = sectors.exact_projectors(verbose=True)
print("sector projector ranks:", sorted(P))
for d, Pd in P.items():
    Pn = np.array(Pd.evalf(30), dtype=complex)
    C.check(f"P_{d} is an orthogonal projector of rank {d}",
            lambda M: np.abs(M @ M - M).max() < 1e-12 and np.abs(M - M.conj().T).max() < 1e-12
            and abs(np.trace(M) - d) < 1e-12, Pn, Pn + 1e-3 * np.eye(7), "add 1e-3 I")

def cheb_U(n, x):
    u0, u1 = lib.Q5(1), 2 * x
    if n == 0:
        return u0
    for _ in range(n - 1):
        u0, u1 = u1, 2 * x * u1 - u0
    return u1

# exact sector characters on class representatives
chi_sec = {}
for d, Pd in P.items():
    vals = []
    for cls in classes:
        Dh = lib.D_sym(6, lib.su2_sym(cls[0]))
        vals.append(sp.nsimplify(sp.expand((Pd * Dh).trace())))
    chi_sec[d] = vals
    print(f"chi of {d}-dim sector on classes:", vals)
# invariance of P under the group (commutes with generators)
def commutes_exactly(Pd, gens):
    for g in gens:
        Dg_ = lib.D_sym(6, lib.su2_sym(g))
        Z = (Dg_ * Pd - Pd * Dg_).applyfunc(sp.expand)
        if not all(Z[i, k] == 0 for i in range(7) for k in range(7)):
            return False
    return True

QOUT = (lib.Q5(lib.Fr(3, 5)), lib.Q5(lib.Fr(4, 5)), lib.Q5(0), lib.Q5(0))
for d, Pd in P.items():
    C.check(f"P_{d} commutes exactly with D^3(q1), D^3(q2)", lambda gens: commutes_exactly(Pd, gens),
            (lib.Q1, lib.Q2), (lib.Q1, QOUT), "replace q2 by 3/5 + 4/5 i (not in Gamma)")
# irreducibility: <chi,chi> = 1
for d in P:
    nrm = sum(len(cl) * sp.expand(chi_sec[d][i] * sp.conjugate(chi_sec[d][i]))
              for i, cl in enumerate(classes)) / order
    nrm = sp.nsimplify(sp.expand(nrm))
    C.check(f"<chi_{d}, chi_{d}> == 1 (irreducible)", lambda z: z == 1, nrm, nrm + 1, "add 1")

homdims = {}
for d in P:
    row = {}
    for n in range(0, 19):
        s = 0
        for i, cl in enumerate(classes):
            chij = cheb_U(n, cl[0][0]).sym()
            s += len(cl) * sp.conjugate(chi_sec[d][i]) * chij
        val = sp.nsimplify(sp.expand(s / order))
        assert val.is_integer and val >= 0, (d, n, val)
        row[n] = int(val)
    homdims[d] = row
    print(f"{d}-dim sector, dim Hom(sigma, V_(n/2)) for n=0..18:", [row[n] for n in range(19)])

# cross-check Chebyshev characters against traces of explicit D^j on all elements, and
# Hom dims by numeric averaging over all 120 elements with explicit matrices
Us = np.array([lib.su2_num(h) for h in G])
a, b, c, dd = Us[:, 0, 0], Us[:, 0, 1], Us[:, 1, 0], Us[:, 1, 1]
D3 = lib.D_num(6, a, b, c, dd)
maxerr_ch = 0
num_dims = {}
for d, Pd in P.items():
    Pn = np.array(Pd.evalf(30), dtype=complex)
    chis = np.einsum("ij,gji->g", Pn, D3)
    row = {}
    for n in range(19):
        Dn = lib.D_num(n, a, b, c, dd)
        tr = np.einsum("gii->g", Dn)
        ch = np.array([float(cheb_U(n, h[0])) for h in G])
        maxerr_ch = max(maxerr_ch, np.abs(tr - ch).max())
        row[n] = (np.conj(chis) * tr).sum() / order
    num_dims[d] = row
err_dims = max(abs(num_dims[d][n] - homdims[d][n]) for d in P for n in range(19))
C.check(f"Chebyshev character == trace of explicit D^j on all 120 elements (err {maxerr_ch:.1e})",
        lambda e: e < 1e-9, maxerr_ch, maxerr_ch + 1, "add 1")
C.check(f"numeric group average of explicit matrices == exact Hom dims (err {err_dims:.1e})",
        lambda e: e < 1e-9, err_dims,
        max(abs(num_dims[d][n] - homdims[d][(n + 2) % 19]) for d in P for n in range(19)),
        "compare against dims shifted by two levels")
# secondary identification: Hom dims must not change
P2, _ = sectors.exact_projectors(ident=lib.su2_secondary)
Us2 = np.array([lib.su2_num(h, lib.su2_secondary) for h in G])
a2, b2, c2, d2 = Us2[:, 0, 0], Us2[:, 0, 1], Us2[:, 1, 0], Us2[:, 1, 1]
D3b = lib.D_num(6, a2, b2, c2, d2)
e2 = 0
for d, Pd in P2.items():
    Pn = np.array(Pd.evalf(30), dtype=complex)
    chis = np.einsum("ij,gji->g", Pn, D3b)
    for n in range(19):
        tr = np.einsum("gii->g", lib.D_num(n, a2, b2, c2, d2))
        e2 = max(e2, abs((np.conj(chis) * tr).sum() / order - homdims[d][n]))
C.check(f"Hom dims identical under the secondary quaternion identification (err {e2:.1e})",
        lambda e: e < 1e-9, e2, e2 + 1, "add 1")
res["item1"] = {"homdims": {str(d): homdims[d] for d in homdims},
                "sector_chars_on_classes": {str(d): [str(x) for x in chi_sec[d]] for d in chi_sec},
                "class_reps_2w": [str(sp.nsimplify((2 * c[0][0]).sym())) for c in classes],
                "class_sizes": [len(c) for c in classes],
                "projector_class_size": info["class_size"],
                "projector_class_eigs": [str(x) for x in info["eigs"]],
                "declaration": "DERIVED"}
res["checks"] = C.records
res["all_ok"] = C.all_ok()
json.dump(res, open(lib.ROOM / "item01.json", "w"), indent=1, default=str)
print("ALL OK" if C.all_ok() else "SOME CHECKS FAILED")
