"""Shared library for the stage-1 audit. Own implementations only.

Exact quaternion arithmetic over Q(sqrt5), the group generated by q1, q2,
SU(2) identifications, D^j (exact sympy and numeric numpy), CG coefficients
(Racah formula, exact) plus an independent highest-weight/lowering construction,
and a check harness in which every PASS has a mutation that must FAIL.
"""
from fractions import Fraction as Fr
from functools import lru_cache
from math import factorial, comb
import pathlib

import numpy as np
import sympy as sp

ROOM = pathlib.Path(__file__).parent


# ---------------------------------------------------------------- Q(sqrt5)
class Q5:
    __slots__ = ("a", "b")

    def __init__(self, a, b=0):
        self.a = Fr(a)
        self.b = Fr(b)

    def __add__(s, o):
        o = o if isinstance(o, Q5) else Q5(o)
        return Q5(s.a + o.a, s.b + o.b)

    __radd__ = __add__

    def __neg__(s):
        return Q5(-s.a, -s.b)

    def __sub__(s, o):
        return s + (-(o if isinstance(o, Q5) else Q5(o)))

    def __rsub__(s, o):
        return Q5(o) - s

    def __mul__(s, o):
        o = o if isinstance(o, Q5) else Q5(o)
        return Q5(s.a * o.a + 5 * s.b * o.b, s.a * o.b + s.b * o.a)

    __rmul__ = __mul__

    def inv(s):
        den = s.a * s.a - 5 * s.b * s.b
        return Q5(s.a / den, -s.b / den)

    def __truediv__(s, o):
        o = o if isinstance(o, Q5) else Q5(o)
        return s * o.inv()

    def __eq__(s, o):
        o = o if isinstance(o, Q5) else Q5(o)
        return s.a == o.a and s.b == o.b

    def __hash__(s):
        return hash((s.a, s.b))

    def __float__(s):
        return float(s.a) + float(s.b) * 5 ** 0.5

    def sym(s):
        return sp.Rational(s.a.numerator, s.a.denominator) + sp.Rational(
            s.b.numerator, s.b.denominator) * sp.sqrt(5)

    def __repr__(s):
        return f"({s.a}+{s.b}r5)"


def qmul(p, q):
    w1, x1, y1, z1 = p
    w2, x2, y2, z2 = q
    return (w1 * w2 - x1 * x2 - y1 * y2 - z1 * z2,
            w1 * x2 + x1 * w2 + y1 * z2 - z1 * y2,
            w1 * y2 - x1 * z2 + y1 * w2 + z1 * x2,
            w1 * z2 + x1 * y2 - y1 * x2 + z1 * w2)


def qconj(q):
    return (q[0], -q[1], -q[2], -q[3])


def qnorm2(q):
    return q[0] * q[0] + q[1] * q[1] + q[2] * q[2] + q[3] * q[3]


PHI = Q5(Fr(1, 2), Fr(1, 2))
PHIINV = Q5(Fr(-1, 2), Fr(1, 2))
HALF = Fr(1, 2)
Q1 = (Q5(HALF), Q5(HALF), Q5(HALF), Q5(HALF))
Q2 = (PHI * HALF, PHIINV * HALF, Q5(HALF), Q5(0))
QID = (Q5(1), Q5(0), Q5(0), Q5(0))


def closure(gens):
    elems = {QID}
    frontier = [QID]
    while frontier:
        new = []
        for e in frontier:
            for g in gens:
                p = qmul(e, g)
                if p not in elems:
                    elems.add(p)
                    new.append(p)
        frontier = new
    return elems


def group():
    G = closure([Q1, Q2])
    return sorted(G, key=lambda q: tuple(float(c) for c in q))


def conj_classes(G):
    Gs = set(G)
    left = set(G)
    classes = []
    while left:
        x = next(iter(sorted(left, key=lambda q: tuple(float(c) for c in q))))
        cl = {qmul(qmul(g, x), qconj(g)) for g in G}
        assert cl <= Gs
        classes.append(sorted(cl, key=lambda q: tuple(float(c) for c in q)))
        left -= cl
    return classes


# ---------------------------------------------------------------- SU(2) maps
def su2_primary(q):
    """w + xi + yj + zk -> w I - i(x sx + y sy + z sz)."""
    w, x, y, z = q
    return [[(w, -z), (-y, -x)], [(y, -x), (w, z)]]   # (re, im) pairs


def su2_secondary(q):
    """i -> i sz, j -> i sy, k -> i sx."""
    w, x, y, z = q
    return [[(w, x), (y, z)], [(-y, z), (w, -x)]]


def su2_sym(q, ident=su2_primary):
    M = ident(q)
    return sp.Matrix(2, 2, lambda r, c: M[r][c][0].sym() + sp.I * M[r][c][1].sym())


def su2_num(q, ident=su2_primary):
    M = ident(q)
    return np.array([[float(M[r][c][0]) + 1j * float(M[r][c][1]) for c in range(2)]
                     for r in range(2)])


def su2_from_quat_float(w, x, y, z, ident="primary"):
    """Vectorised float version (arrays)."""
    if ident == "primary":
        return (w - 1j * z, -y - 1j * x, y - 1j * x, w + 1j * z)
    return (w + 1j * x, y + 1j * z, -y + 1j * z, w - 1j * x)


# ---------------------------------------------------------------- D^j
def Nfac(n, i):
    return factorial(i) * factorial(n - i)


def D_num(n, a, b, c, d):
    """D^{n/2} for arrays a,b,c,d of shape S; returns array S+(n+1,n+1).
    Index i = j + m (0..n). Basis v_i = x^i y^(n-i)/sqrt(i!(n-i)!).
    U acts by P(x,y) -> P(ax+cy, bx+dy)."""
    a, b, c, d = (np.asarray(t, dtype=complex) for t in (a, b, c, d))
    S = a.shape
    out = np.zeros(S + (n + 1, n + 1), dtype=complex)
    apow = [np.ones(S, complex)]
    bpow = [np.ones(S, complex)]
    cpow = [np.ones(S, complex)]
    dpow = [np.ones(S, complex)]
    for _ in range(n):
        apow.append(apow[-1] * a)
        bpow.append(bpow[-1] * b)
        cpow.append(cpow[-1] * c)
        dpow.append(dpow[-1] * d)
    for k in range(n + 1):
        # (ax+cy)^k (bx+dy)^(n-k): coefficient of x^i y^(n-i)
        for s in range(k + 1):
            t1 = comb(k, s) * apow[s] * cpow[k - s]
            for t in range(n - k + 1):
                i = s + t
                out[..., i, k] += t1 * comb(n - k, t) * bpow[t] * dpow[n - k - t]
    for i in range(n + 1):
        for k in range(n + 1):
            out[..., i, k] *= (Nfac(n, i) / Nfac(n, k)) ** 0.5
    return out


def D_sym(n, U):
    a, b, c, d = U[0, 0], U[0, 1], U[1, 0], U[1, 1]
    M = sp.zeros(n + 1, n + 1)
    x, y = sp.symbols("x y")
    for k in range(n + 1):
        pol = sp.Poly(sp.expand((a * x + c * y) ** k * (b * x + d * y) ** (n - k)), x, y)
        for i in range(n + 1):
            coef = pol.coeff_monomial(x ** i * y ** (n - i))
            M[i, k] = sp.expand(coef * sp.sqrt(sp.Rational(Nfac(n, i), Nfac(n, k))))
    return M


# ---------------------------------------------------------------- spin matrices
def spin_mats_sym(n):
    """Jz, J+, J- for spin n/2 in basis index i=j+m, CS phase, exact."""
    j = sp.Rational(n, 2)
    Jz = sp.zeros(n + 1, n + 1)
    Jp = sp.zeros(n + 1, n + 1)
    for i in range(n + 1):
        m = i - j
        Jz[i, i] = m
        if i < n:
            Jp[i + 1, i] = sp.sqrt((j - m) * (j + m + 1))
    return Jz, Jp, Jp.T


# ---------------------------------------------------------------- CG (Racah)
@lru_cache(maxsize=None)
def cg(j1, m1, j2, m2, J, M):
    """<j1 m1; j2 m2 | J M>, integer spins, exact (sympy), Condon-Shortley (Racah formula)."""
    if m1 + m2 != M or abs(m1) > j1 or abs(m2) > j2 or abs(M) > J:
        return sp.Integer(0)
    if J < abs(j1 - j2) or J > j1 + j2:
        return sp.Integer(0)
    f = factorial
    pre = sp.Rational((2 * J + 1) * f(j1 + j2 - J) * f(j1 - j2 + J) * f(-j1 + j2 + J),
                      f(j1 + j2 + J + 1))
    pre2 = f(j1 + m1) * f(j1 - m1) * f(j2 + m2) * f(j2 - m2) * f(J + M) * f(J - M)
    s = sp.Integer(0)
    for k in range(0, j1 + j2 - J + 1):
        dens = [k, j1 + j2 - J - k, j1 - m1 - k, j2 + m2 - k, J - j2 + m1 + k, J - j1 - m2 + k]
        if min(dens) < 0:
            continue
        p = 1
        for t in dens:
            p *= f(t)
        s += sp.Rational((-1) ** k, p)
    return sp.sqrt(pre * pre2) * s


@lru_cache(maxsize=None)
def cg_lowering_table(j1, j2, J):
    """Independent construction: highest weight vector of spin J in V_j1 (x) V_j2
    (kernel of J+), CS sign <j1 j1; j2 J-j1|J J> > 0, then lowering with J-.
    Returns dict (m1, m2, M) -> exact coefficient."""
    def a(j, m):  # J+ |j m> = a |j m+1>
        return sp.sqrt(sp.Integer((j - m) * (j + m + 1)))

    def am(j, m):  # J- |j m> = am |j m-1>
        return sp.sqrt(sp.Integer((j + m) * (j - m + 1)))
    # highest weight: coefficients c[m1], m2 = J - m1
    m1s = [m1 for m1 in range(-j1, j1 + 1) if abs(J - m1) <= j2]
    c = {}
    top = max(m1s)
    c[top] = sp.Integer(1)
    for m1 in sorted(m1s, reverse=True)[1:]:
        # condition on coefficient of |m1+1, J-m1>:
        # c[m1] a(j2, J-m1-1)?? derive: J+ acting on |m1, J-m1>: a(j1,m1)|m1+1,J-m1> + a(j2,J-m1)|m1,J-m1+1>
        # coefficient of |m1+1, J-m1> collects c[m1] a(j1,m1) + c[m1+1] a(j2, J-m1-1) = 0
        c[m1] = sp.simplify(-c[m1 + 1] * a(j2, J - m1 - 1) / a(j1, m1))
    nrm = sp.sqrt(sp.nsimplify(sum(sp.expand(v ** 2) for v in c.values())))
    for k in c:
        c[k] = sp.radsimp(c[k] / nrm)
    if j1 in c and sp.N(c[j1]) < 0:
        for k in c:
            c[k] = -c[k]
    state = {(m1, J - m1): c[m1] for m1 in c}
    table = {}
    for (m1, m2), v in state.items():
        table[(m1, m2, J)] = v
    M = J
    while M > -J:
        new = {}
        for (m1, m2), v in state.items():
            if m1 > -j1:
                key = (m1 - 1, m2)
                new[key] = new.get(key, 0) + v * am(j1, m1)
            if m2 > -j2:
                key = (m1, m2 - 1)
                new[key] = new.get(key, 0) + v * am(j2, m2)
        den = am(J, M)
        M -= 1
        state = {k: sp.radsimp(sp.expand(v / den)) for k, v in new.items()}
        for (m1, m2), v in state.items():
            table[(m1, m2, M)] = v
    return table


# ---------------------------------------------------------------- vectors in V_j (lists, index m+j)
def theta(x):
    """(Theta x)_m = (-1)^m conj(x_{-m})."""
    j = (len(x) - 1) // 2
    # integer sign: (-1) ** negative_int is a Python float and would break exactness
    return [sp.expand((1 if (i - j) % 2 == 0 else -1) * sp.conjugate(x[2 * j - i]))
            for i in range(2 * j + 1)]


def couple(x, y, J):
    j1 = (len(x) - 1) // 2
    j2 = (len(y) - 1) // 2
    if J < abs(j1 - j2) or J > j1 + j2:
        return None
    out = []
    for M in range(-J, J + 1):
        s = 0
        for m1 in range(-j1, j1 + 1):
            m2 = M - m1
            if abs(m2) > j2:
                continue
            xv = x[m1 + j1]
            yv = y[m2 + j2]
            if xv == 0 or yv == 0:
                continue
            s += cg(j1, m1, j2, m2, J, M) * xv * yv
        out.append(sp.expand(s))
    return out


def inner(x, y):
    return sp.expand(sum(sp.conjugate(a) * b for a, b in zip(x, y)))


# ---------------------------------------------------------------- checks
class Checker:
    """Each check: a predicate evaluated on the real object and on a mutated object.
    PASS only if real -> True and mutant -> False."""

    def __init__(self, name):
        self.name = name
        self.records = []

    def check(self, label, pred, real, mutant, mutation_desc):
        r = bool(pred(real))
        m = bool(pred(mutant))
        ok = r and not m
        status = "PASS" if ok else ("FAIL" if not r else "FAIL(mutant-not-caught)")
        self.records.append({"label": label, "status": status, "real": r,
                             "mutant_result": m, "mutation": mutation_desc})
        print(f"[{status}] {label}   | mutation: {mutation_desc} -> mutant {'passed (BAD)' if m else 'failed (good)'}")
        return ok

    def all_ok(self):
        return all(r["status"] == "PASS" for r in self.records)
